if [[ -f $HOME/.bashrc ]]; then source $HOME/.bashrc; fi
if [[ -f $HOME/.bashrc.local ]]; then source $HOME/.bashrc.local; fi
export PATH=$PATH:/Applications/Postgres.app/Contents/Versions/9.4/bin
export GOPATH=~/Documents/code/go
export GOBIN=$GOPATH/bin
export PATH=$PATH:$GOBIN
if [ -f $(brew --prefix)/etc/bash_completion ]; then
  . $(brew --prefix)/etc/bash_completion
fi
export PATH="/usr/local/opt/libxml2/bin:$PATH"
