# Environment variables that should be available to all shells

# Homebrew paths are handled by `eval $(/opt/homebrew/bin/brew shellenv)` in .zshrc
export PATH="/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/mysql/bin:/usr/local/heroku/bin:$PATH"

# This will find the latest version in the Postgres.app
if [ -d "/Applications/Postgres.app/Contents/Versions" ]; then
  export PATH="$PATH:$(find /Applications/Postgres.app/Contents/Versions -maxdepth 1 -type d | sort -r | head -n1)/bin"
fi

# NVM setup
export NVM_DIR="$HOME/.nvm"
[ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"
[ -s "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm"

# SDKMAN setup
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"