tap "goldcaddy77/firefox"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
brew "automake"
brew "sqlite"
brew "bash-completion"
brew "libffi"
brew "cmake"
brew "dnsmasq", restart_service: true
brew "icu4c"
brew "harfbuzz"
brew "python@3.9", link: false
brew "ffmpeg"
brew "gdk-pixbuf"
brew "ghostscript"
brew "git"
brew "gnupg"
brew "pango"
brew "hub"
brew "hyperscan"
brew "shared-mime-info"
brew "libheif"
brew "imagemagick"
brew "jansson"
brew "jq"
brew "launch_socket_server", restart_service: true
brew "launchdns", restart_service: true
brew "libcroco"
brew "libssh"
brew "libxml2"
brew "readline"
brew "ruby"
brew "macvim", args: ["HEAD"]
brew "md5sha1sum"
brew "memcached", restart_service: true
brew "mkcert"
brew "protobuf"
brew "nginx", restart_service: true
brew "node"
brew "node-build"
brew "nodenv"
brew "tmux"
brew "overmind"
brew "pidof"
brew "postgresql"
brew "postgresql@9.6"
brew "python@2"
brew "ruby-build"
brew "rbenv"
brew "rbenv-bundler-ruby-version"
brew "reattach-to-user-namespace"
brew "redis", restart_service: true
brew "rlwrap"
brew "ruby-install"
brew "socat"
brew "the_silver_searcher"
brew "tmate"
brew "watchman"
brew "yarn"
cask "1password"
cask "backblaze"
cask "barrier"
cask "chromedriver"
cask "dropbox"
cask "encryptme"
cask "firefox"
cask "flux"
cask "google-chrome"
cask "hammerspoon"
cask "keybase"
cask "muzzle"
cask "ngrok"
cask "postman"
cask "spotify"
cask "xquartz"
cask "zoom"
